alter session set nls_date_format='YYYY/MM/DD HH24:MI:SS';

SELECT * FROM V_RECORD;
create OR REPLACE view v_record AS
SELECT RECORD_SUBJECT_ID
, (SELECT SUBJECT_NAME FROM SUBJECT WHERE RECORD_SUBJECT_ID = SUBJECT_ID) AS SUBJECT_NAME
, RECORD_MEM_ID
    , TRUNC(RECORD_START) RECORD_DATE
    , NUMTODSINTERVAL( SUM(RECORD_END - RECORD_START) ,'DAY') DIFFTIME
FROM RECORD 
GROUP BY RECORD_SUBJECT_ID, RECORD_MEM_ID, TRUNC(RECORD_START)
;


SELECT * FROM v_record_WO_SUBJECT;
create OR REPLACE view v_record_WO_SUBJECT AS
SELECT RECORD_MEM_ID
    , TRUNC(RECORD_START) RECORD_DATE
    , NUMTODSINTERVAL( SUM(RECORD_END - RECORD_START) ,'DAY') DIFFTIME
FROM RECORD 
GROUP BY RECORD_MEM_ID, TRUNC(RECORD_START)
;

SELECT * FROM v_record_WO_SUBJECT_W_GROUP;
create OR REPLACE view v_record_WO_SUBJECT_W_GROUP AS
SELECT SGROUP_ID, sgroup_mem_id, RECORD_DATE, DIFFTIME
FROM sgroup_member TS 
LEFT JOIN (SELECT RECORD_MEM_ID
        , TRUNC(RECORD_START) RECORD_DATE
        , NUMTODSINTERVAL( SUM(RECORD_END - RECORD_START) ,'DAY') DIFFTIME
    FROM RECORD 
    GROUP BY RECORD_MEM_ID, TRUNC(RECORD_START)) TR
ON sgroup_mem_id = RECORD_MEM_ID
;

SELECT * FROM v_record_WEEK;
create OR REPLACE view v_record_WEEK AS
SELECT RECORD_MEM_ID
    , NUMTODSINTERVAL( SUM(RECORD_END - RECORD_START) ,'DAY') DIFFTIME
FROM RECORD 
WHERE TRUNC(RECORD_START) BETWEEN TRUNC(SYSDATE-6) AND TRUNC(SYSDATE-0)
GROUP BY RECORD_MEM_ID
;



  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SWITHME"."V_RECORD_SEC" ("RECORD_SUBJECT_ID", "SUBJECT_NAME", "RECORD_MEM_ID", "RECORD_DATE", "DIFFTIME") AS 
  SELECT RECORD_SUBJECT_ID
, (SELECT SUBJECT_NAME FROM SUBJECT WHERE RECORD_SUBJECT_ID = SUBJECT_ID) AS SUBJECT_NAME
, RECORD_MEM_ID
, TRUNC(RECORD_START) RECORD_DATE
, SUM(RECORD_END - RECORD_START) *24*60*60 DIFFTIME
FROM RECORD 
GROUP BY RECORD_SUBJECT_ID, RECORD_MEM_ID, TRUNC(RECORD_START);




  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SWITHME"."V_DDAY30" ("DDAY") AS 
  select TRUNC(SYSDATE-30) dday from dual
union
select TRUNC(SYSDATE-29) dday from dual
union
select TRUNC(SYSDATE-28) dday from dual
union
select TRUNC(SYSDATE-27) dday from dual
union
select TRUNC(SYSDATE-26) dday from dual
union
select TRUNC(SYSDATE-25) dday from dual
union
select TRUNC(SYSDATE-24) dday from dual
union
select TRUNC(SYSDATE-23) dday from dual
union
select TRUNC(SYSDATE-22) dday from dual
union
select TRUNC(SYSDATE-21) dday from dual
union
select TRUNC(SYSDATE-20) dday from dual
union
select TRUNC(SYSDATE-19) dday from dual
union
select TRUNC(SYSDATE-18) dday from dual
union
select TRUNC(SYSDATE-17) dday from dual
union
select TRUNC(SYSDATE-16) dday from dual
union
select TRUNC(SYSDATE-15) dday from dual
union
select TRUNC(SYSDATE-14) dday from dual
union
select TRUNC(SYSDATE-13) dday from dual
union
select TRUNC(SYSDATE-12) dday from dual
union
select TRUNC(SYSDATE-11) dday from dual
union
select TRUNC(SYSDATE-10) dday from dual
union
select TRUNC(SYSDATE-9) dday from dual
union
select TRUNC(SYSDATE-8) dday from dual
union
select TRUNC(SYSDATE-7) dday from dual
union
select TRUNC(SYSDATE-6) dday from dual
union
select TRUNC(SYSDATE-5) dday from dual
union
select TRUNC(SYSDATE-4) dday from dual
union
select TRUNC(SYSDATE-3) dday from dual
union
select TRUNC(SYSDATE-2) dday from dual
union
select TRUNC(SYSDATE-1) dday from dual
union
select TRUNC(SYSDATE-0) dday from dual;



  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SWITHME"."V_DDAY4" ("DDAY") AS 
  select TRUNC(SYSDATE-3) dday from dual
union
select TRUNC(SYSDATE-2) dday from dual
union
select TRUNC(SYSDATE-1) dday from dual
union
select TRUNC(SYSDATE-0) dday from dual;


  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SWITHME"."V_MMONTH12" ("MMONTH") AS 
  SELECT TRUNC(ADD_MONTHS(SYSDATE, -11),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -10),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -9),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -8),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -7),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -6),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -5),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -4),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -3),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -2),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -1),'month') AS MMONTH FROM  DUAL UNION  SELECT TRUNC(ADD_MONTHS(SYSDATE, -0),'month') AS MMONTH FROM  DUAL;
