--record RECORD_START,RECORD_END -> SYSDATE로 변경
--ALTER TABLE RECORD MODIFY(RECORD_START DATE);
--ALTER TABLE RECORD MODIFY(RECORD_END DATE);
----subject도 같이 변경 SUBJECT_ADD_DATE,SUBJECT_DEL_DATE 
--ALTER TABLE SUBJECT MODIFY(SUBJECT_ADD_DATE DATE);
--ALTER TABLE SUBJECT MODIFY(SUBJECT_DEL_DATE DATE);
desc subject;
select * from record order by record_start asc;
------ 2월
exec PRO_RECORD_MMDD_MORNING('won','JAVA',2,1);
exec PRO_RECORD_MMDD_LUNCH('won','CSS',2,1);
exec PRO_RECORD_MMDD_DINNER('won','SQL',2,1);

exec PRO_RECORD_MMDD_MORNING('won','SQL',2,2);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',2,2);
exec PRO_RECORD_MMDD_DINNER('won','JAVA',2,2);

exec PRO_RECORD_MMDD_MORNING('won','JAVA',2,5);
exec PRO_RECORD_MMDD_LUNCH('won','SQL',2,5);
exec PRO_RECORD_MMDD_DINNER('won','CSS',2,5);

exec PRO_RECORD_MMDD_MORNING('won','CSS',2,10);
exec PRO_RECORD_MMDD_LUNCH('won','SQL',2,10);
exec PRO_RECORD_MMDD_DINNER('won','JAVA',2,10);

exec PRO_RECORD_MMDD_MORNING('won','JAVA',2,11);
exec PRO_RECORD_MMDD_LUNCH('won','지구과학',2,11);
exec PRO_RECORD_MMDD_DINNER('won','CSS',2,11);

exec PRO_RECORD_MMDD_MORNING('won','JAVA',2,12);
exec PRO_RECORD_MMDD_LUNCH('won','SQL',2,12);
exec PRO_RECORD_MMDD_DINNER('won','CSS',2,12);

exec PRO_RECORD_MMDD_MORNING('won','CSS',2,22);
exec PRO_RECORD_MMDD_LUNCH('won','HTML',2,22);
exec PRO_RECORD_MMDD_DINNER('won','JAVA',2,22);

exec PRO_RECORD_MMDD_MORNING('won','HTML',2,25);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',2,25);
exec PRO_RECORD_MMDD_DINNER('won','지구과학',2,25);
------ 3월
exec PRO_RECORD_MMDD_MORNING('won','HTML',3,2);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,2);
exec PRO_RECORD_MMDD_DINNER('won','CSS',3,2);

exec PRO_RECORD_MMDD_MORNING('won','SQL',3,5);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,5);
exec PRO_RECORD_MMDD_DINNER('won','CSS',3,5);

exec PRO_RECORD_MMDD_MORNING('won','지구과학',3,11);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,11);
exec PRO_RECORD_MMDD_DINNER('won','SQL',3,11);

exec PRO_RECORD_MMDD_MORNING('won','지구과학',3,12);
exec PRO_RECORD_MMDD_LUNCH('won','CSS',3,12);
exec PRO_RECORD_MMDD_DINNER('won','SQL',3,12);

exec PRO_RECORD_MMDD_MORNING('won','JAVA',3,22);
exec PRO_RECORD_MMDD_LUNCH('won','SQL',3,22);
exec PRO_RECORD_MMDD_DINNER('won','HTML',3,22);

exec PRO_RECORD_MMDD_MORNING('won','HTML',3,25);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,25);
exec PRO_RECORD_MMDD_DINNER('won','HTML',3,25);

exec PRO_RECORD_MMDD_MORNING('won','HTML',3,26);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,26);
exec PRO_RECORD_MMDD_DINNER('won','SQL',3,26);

exec PRO_RECORD_MMDD_MORNING('won','지구과학',3,27);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,27);
exec PRO_RECORD_MMDD_DINNER('won','HTML',3,27);

exec PRO_RECORD_MMDD_MORNING('won','HTML',3,28);
exec PRO_RECORD_MMDD_LUNCH('won','JAVA',3,28);
exec PRO_RECORD_MMDD_DINNER('won','CSS',3,28);
--아이디, 과목이름, 날짜 / 4월로 지정됨
exec PRO_RECORD_INSERT_MORNING('won','JAVA','02');
exec PRO_RECORD_INSERT_LUNCH('won','JAVA','02');
exec PRO_RECORD_INSERT_DINNER('won','HTML','02');
--16일
exec PRO_RECORD_INSERT_MORNING('won','HTML','16');
exec PRO_RECORD_INSERT_LUNCH('won','CSS','16');
exec PRO_RECORD_INSERT_DINNER('won','JAVA','16');
--17일
exec PRO_RECORD_INSERT_DINNER('won','CSS','17');
exec PRO_RECORD_INSERT_LUNCH('won','JAVA','17');
exec PRO_RECORD_INSERT_DINNER('won','HTML','17');
--18일
exec PRO_RECORD_INSERT_MORNING('won','SQL','18');
exec PRO_RECORD_INSERT_LUNCH('won','JAVA','18');
exec PRO_RECORD_INSERT_DINNER('won','HTML','18');

--19일
exec PRO_RECORD_INSERT_MORNING('won','SQL','19');
exec PRO_RECORD_INSERT_LUNCH('won','SQL','19');
exec PRO_RECORD_INSERT_DINNER('won','JAVA','19');

exec PRO_RECORD_INSERT_MORNING('song','JAVA','19');
exec PRO_RECORD_INSERT_LUNCH('song','spring','19');
exec PRO_RECORD_INSERT_DINNER('song','C#','19');
--21일
exec PRO_RECORD_INSERT_MORNING('won','HTML','21');
exec PRO_RECORD_INSERT_LUNCH('won','SQL','21');
exec PRO_RECORD_INSERT_DINNER('won','CSS','21');


--22일
exec PRO_RECORD_INSERT_MORNING('song','JAVA','22');
exec PRO_RECORD_INSERT_LUNCH('song','spring','22');
exec PRO_RECORD_INSERT_DINNER('song','C#','22');

exec PRO_RECORD_INSERT_MORNING('won','JAVA','22');
exec PRO_RECORD_INSERT_LUNCH('won','SQL','22');
exec PRO_RECORD_INSERT_DINNER('won','CSS','22');

exec PRO_RECORD_INSERT_MORNING('b','자바','22');
exec PRO_RECORD_INSERT_LUNCH('b','파이썬','22');


--23일
exec PRO_RECORD_INSERT_MORNING('won','SQL','23');
exec PRO_RECORD_INSERT_LUNCH('won','JAVA','23');
exec PRO_RECORD_INSERT_DINNER('won','CSS','23');

--30일
exec PRO_RECORD_INSERT_MORNING('won','CSS','30');
exec PRO_RECORD_INSERT_LUNCH('won','SQL','30');
exec PRO_RECORD_INSERT_DINNER('won','JAVA','30');

exec PRO_RECORD_INSERT_MORNING('song','JAVA','30');
exec PRO_RECORD_INSERT_LUNCH('song','spring','30');
exec PRO_RECORD_INSERT_DINNER('song','C#','30');

--hyo
exec PRO_RECORD_MMDD_MORNING('won','JAVA',2,1);
exec PRO_RECORD_MMDD_LUNCH('won','C#',2,1);
exec PRO_RECORD_MMDD_DINNER('won','SQL',2,1);


commit;
